version: '2'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    links:
      - db
    environment:
      - POSTGRES_URI_DOCKER=db:5432

  db:
    image: postgres:9.5
    ports:
      - "5432"
    environment:
      - POSTGRES_DB=samples
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
