version: '2'
services:

  web:
    image: web-app-angular2:X.X
    entrypoint: bash -c "while ! timeout 1 wget -qO- http://selenium:4444/wd/hub > /dev/null ; do sleep 1; done; protractor --seleniumAddress http://selenium:4444/wd/hub config/conf.js --params.SUT_HTTP_HOST web --params.SUT_HTTP_PORT 8080"

    ports:
      - "8080:8080"
    links:
      - db

  db:
    image: postgres:9.5
    ports:
      - "5432"
    environment:
      - POSTGRES_DB=samples
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
